### ISSUE TITLE
Question about use with Quorum Queues (RMQ 3.8+)

### ISSUE THREAD

**Issue by Eric24** [jwalton/node-amqp-connection-manager#119]
Is there any known issue using this library with Quorum Queues (or even Mirrored Queues)? Specifically, it's my understanding that when connecting to a RMQ cluster node and consuming a queue, if that node doesn't hold the "master replica" of the queue, a "redirect" is returned with the address of the target cluster node that does, and expects the client to reconnect to that cluster node.

**Comment by balthazar** [comment]
Would love to know that too

**Comment by jwalton** [comment]
Basically this library is a thin wrapped around [amqplib](https://www.npmjs.com/package/amqplib) that watches to see if the connection dies, and if it does it tries to reconnect.  I'm not actively using RabbitMQ or AMQP right now, so questions like this would better be directed there.  If there's something that needs to change in this library to handle connecting to multiple servers, I'd welcome a PR.

**Comment by luddd3** [comment]
I don't think there's any redirect involved. What would happen if a connection would use two queues on different nodes?

Here it states that the quorum queues deliver to each connection from local replicas if the connected node doesn't have the master.
https://blog.rabbitmq.com/posts/2020/06/quorum-queues-local-delivery
