### ISSUE TITLE
connect fail with password contain special world

### ISSUE THREAD

**Issue by meng-chiang** [jwalton/node-amqp-connection-manager#120]
In AmqpConnectionManager.js, library will try to parse url then format url.
`const amqpUrl = _url.default.parse(urlString);`
then
`return _amqplib.default.connect(_url.default.format(amqpUrl), connectionOptions).then(connection => { .... }
`

I tried to encode my username/pwd in connect url.
```
var url =require('url')
var user = encodeURIComponent('us:er');
var password = encodeURIComponent('u:AK}G6^`)6rA6WUYEhG');
var uri = 'amqp://' + user + ':' + password + '@localhost/';

console.log('encode uri: ',uri);
// encode uri:  amqp://us%3Aer:u%3AAK%7DG6%5E%60)6rA6WUYEhG@localhost/

var parsed = url.parse(uri);
console.log(parsed)
/*
Url {
  protocol: 'amqp:',
  slashes: true,
  auth: 'us:er:u:AK}G6^`)6rA6WUYEhG',
  host: 'localhost',
  port: null,
  hostname: 'localhost',
  hash: null,
  search: null,
  query: null,
  pathname: '/',
  path: '/',
  href: 'amqp://us:er:u:AK%7DG6%5E%60)6rA6WUYEhG@localhost/' }
*/
console.log('format uri:', url.format(parsed))
// format uri: amqp://us:er:u:AK%7DG6%5E%60)6rA6WUYEhG@localhost/
```
password didn't format correct with special world. 
Any suggestion would be helpful. Thanks!

**Comment by jwalton** [comment]
We pass connection options straight through to [amqplib](https://www.npmjs.com/package/amqplib), so you'd be better off asking there.
