### ISSUE TITLE
Question: possible to reset the memory queue ?

### ISSUE THREAD

**Issue by natcl** [jwalton/node-amqp-connection-manager#127]
I really like the idea of the manager queuing message in-memory when the broker is not connected. However, is there a mechanism to limit the number of queued messages or an option to clear the queue ?
I worry that if my connection is offline for a while it will just fill memory....
I assume one technique could be to check the queue size and not send messages when the queue gets to a certain limit ?

**Comment by jwalton** [comment]
If you'd like to submit a PR that adds a function that clears out [`_messages`](https://github.com/jwalton/node-amqp-connection-manager/blob/master/src/ChannelWrapper.js#L164), I'd be happy to see one.  :)

Originally I'd planned to make this more complicated - make it so you could pass in your own `{queueMessage(), getNextMessage()`} object so you could customize the queue behavior.  But I never got around to doing such a thing.
