### ISSUE TITLE
Wait for drain when publish/sendToQueue returns false

### ISSUE THREAD

**Issue by Eadword** [jwalton/node-amqp-connection-manager#129]
I am trying to read through the code and I know for a fact I have not seen any waits for the `drain` event form `channel`, however, I am not sure if they are needed.

According to the `amqplib` docs, when `publish` or `sendToQueue` returns `false`, you should wait for the `drain` event before re-trying. It _looks_ like the code currently just returns false and leaves it to the user to retry; but that requires accessing `channelWrapper._channel.on('drain', cb)` to do so.

You can find the docs on this at the bottom of [this](http://www.squaremobius.net/amqp.node/channel_api.html#channel_publish) section.

**Comment by SimoneDagna** [comment]
The same goes for `return` event.
Accordingly with: https://www.rabbitmq.com/publishers.html
> When a published message cannot be routed to any queue, and the publisher set the `mandatory` message property to **true**, the message will be returned to it. The publisher must have a returned message handler set up in order to handle the return (e.g. by logging an error or retrying with a different exchange)

`channelWrapper.on('return', cb)` doesn't work.

Direclty attaching event listener using ConfirmChannel inside `setup` callback seems to work but feels wrong.

**Comment by navedmirCM** [comment]
Any update on channel drain? I can the drain event being fired but no messages are getting dropped. Not sure, whether it is handled in this library. I can't find the code where drain is handled

**Comment by richardklafter** [comment]
Reading the code if you always `await` chances are you will never hit the drain issue because this library significantly throttles how quickly you can publish messages. If you just publish 100K+ messages without `await` you will have a bad day.

```js
//This will work fine because the internal setImmediate call will throttle your publishes to 1 per event loop cycle.
for (let index = 0; index < 500000; index++) {
  await channel..publish(exchange, topic, Buffer.from("yourmessage"+index)
}
//This will bust hard!
for (let index = 0; index < 5000000; index++) {
  channel..publish(exchange, topic, Buffer.from("yourmessage"+index)
}
```

I might open a PR to fix or I might just purge this library from our code base largely dependent on if its maintainer responds.

**Comment by jwalton** [comment]
I am more than happy to accept a PR.
