### ISSUE TITLE
how to create  pool connection rabbimq?

### ISSUE THREAD

**Issue by theanhvo** [jwalton/node-amqp-connection-manager#131]
Hi team,
how to create pool connection to rabbmq?
thanks.

**Comment by jwalton** [comment]
Are you trying to connect to multiple rabbitMQs?  Or you just want multiple connections to a single RabbitMQ?

**Comment by rhsobr** [comment]
I don't think that a pool of connections makes sense.
We usually handle one connection to publish and another one to consume.

Otherwise, a pool of channels makes sense, specially when you must publish a lot of stuff.
This lib can help you: https://github.com/coopernurse/node-pool
