### ISSUE TITLE
Channel#checkQueue cannot be used with current implementation

### ISSUE THREAD

**Issue by nieverbe** [jwalton/node-amqp-connection-manager#138]
I would like to check that the reply queue of a RPC call is still available before sending the message. In this way I can revert changes made in the server when the client is not listening anymore.

For this amqplib supports the function **'Channel#checkQueue'**, but this is not available here. Can this be made available?

**Comment by jwalton** [comment]
If you're on the latest version, this should be supported already: https://github.com/jwalton/node-amqp-connection-manager/blob/master/src/ChannelWrapper.js#L447-L449.  This was added in Dec 2019 (https://github.com/jwalton/node-amqp-connection-manager/pull/103).
