### ISSUE TITLE
Messages can be lost forever / wrongly acknowledged

### ISSUE THREAD

**Issue by sanjom** [jwalton/node-amqp-connection-manager#142]
The way I understand the code, everytime we call "publish", we add a new message to the in-memory queue and try to send it. Once the promise resolves (i.e. the message has been publisher confirmed), we remove the first item from this queue, wrongly assuming that this is the one which corresponds to the resolved promise.

However, according to the RabbitMQ docs, the client should not rely on the order of acknowledgements. They can come unordered.

https://www.rabbitmq.com/confirms.html
`
In most cases, RabbitMQ will acknowledge messages to publishers in the same order they were published (this applies for messages published on a single channel). However, publisher acknowledgements are emitted asynchronously and can confirm a single message or a group of messages. The exact moment when a confirm is emitted depends on the delivery mode of a message (persistent vs. transient) and the properties of the queue(s) the message was routed to (see above). Which is to say that different messages can be considered ready for acknowledgement at different times. This means that acknowledgements can arrive in a different order compared to their respective messages. Applications should not depend on the order of acknowledgements when possible.
`

The issue is that should we ever lose the connection, we will try to "re-send" the wrong messages. Some which may not have been acknowledged be lost forever, and others that were already sent will be sent again.

**Comment by jwalton** [comment]
I think you are correct.  Looks like we should be finding the specific message that was acked [here](https://github.com/jwalton/node-amqp-connection-manager/blob/c3a35449cfd52b739b679c39247b4d817c852e4d/src/ChannelWrapper.js#L396).

**Comment by jwalton** [comment]
Thanks for the sharp eyed code review!

**Comment by sanjom** [comment]
Thanks for the quick fix, looks good!

**Comment by jwalton** [comment]
I woke up at 4:30am, and made the mistake of checking my email.  I saw your bug, and thought, "That can't be true."  And then I couldn't get to sleep until I went looking to see if it was true.  :P
