### ISSUE TITLE
Disabling heartbeat

### ISSUE THREAD

**Issue by Abzokhattab** [jwalton/node-amqp-connection-manager#143]
Hello team, 
i use rabbitmq to perform long operations in the consumer handler so I get unexpected close error due to the long operations 

so how can i disable the heartbeat in this package ..
i tried to set `heartbeatIntervalInSeconds` connection attribute to be `0` however that doesnt work and i get this message 
![image](https://user-images.githubusercontent.com/59809993/107387729-c9cf2c80-6afd-11eb-9b35-844c9c542285.png)
also, I tried to disable the manual `ack` but still the same error

**Comment by jwalton** [comment]
Hi!  amqp-connection-manager is really a wrapper around [amqplib](http://www.squaremobius.net/amqp.node/) which handles disconnects from the broker, and queues messages when the broken is unavailable.  I'd suggest you go have a [look at their documentation](http://www.squaremobius.net/amqp.node/channel_api.html#heartbeating).
