### ISSUE TITLE
Can't get a message from a queue. 

### ISSUE THREAD

**Issue by qing8888** [jwalton/node-amqp-connection-manager#149]
```
const msgInQ = await this.channel.get(queueName, {
      noAck: true,
    });
    console.log("msgInQ", msgInQ);
```
After ```publish``` a message,i got ```false``` all the time.I want to get a message from a queue and delete it.

**Comment by jwalton** [comment]
I'm afraid this library is just a thin wrapper around http://www.squaremobius.net/amqp.node/ which provides automatic reconnects when the connection to the broker drops.  If your problem isn't connection related, you should take your question there or to stackoverflow.
