### ISSUE TITLE
Is channelWrapper thread safe?

### ISSUE THREAD

**Issue by alstjd0921** [jwalton/node-amqp-connection-manager#150]
Im going to implement asynchronus code using channelWrapper.
I am well aware that amqp channel is not thread safe. I want to know if channelWrapper can solve this problem.

**Comment by jwalton** [comment]
I'm not sure what you mean by "thread safe", given that there are no threads in node.js.

But, ChannelWrapper just wraps the underlying [amqplib](http://www.squaremobius.net/amqp.node/) channel - this library only handles automatically reconnecting when the underlying connection drops, so if you want to change the behavior of an amqp channel, the place to do that would be in amqplib.
