### ISSUE TITLE
How to connect with plain password method

### ISSUE THREAD

**Issue by ekumahost** [jwalton/node-amqp-connection-manager#151]
Hello Guys, just introduced the package to an old project but the connect is not firing at all using credentials.plain
my script:

```
//const amqp = require('amqplib/callback_api');
const amqp = require('amqp-connection-manager');
        const opt = { credentials: require('amqplib').credentials.plain(process.env.RABBIT_USERNAME, process.env.RABBIT_PASSWORD), clientProperties: {connection_name: "subs"} };

const connection = amqp.connect([process.env.RABBIT_SERVER], opt);
        connection.on('connect', () => console.log('Connected!'));
        connection.on('disconnect', err => console.log('Disconnected.', err.stack));

```

it keep logging `Disconnected.` but not the `Connected!`

**Comment by jwalton** [comment]
It sounds like it's not successfully connecting at all.  What's `err.stack` here?  Does it work when you try with `amqplib` directly?

**Comment by ekumahost** [comment]
`err.stack` is undefined
amqplib actually connects.

**Comment by ekumahost** [comment]
oh, it throws error
`OperationalError: Handshake terminated by server: 403 (ACCESS-REFUSED) with message "ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.`

**Comment by jwalton** [comment]
Try:

```
amqp.connect([process.env.RABBIT_SERVER], { connectionOptions: opt });
```

?

**Comment by ekumahost** [comment]
> Try:
> 
> ```
> amqp.connect([process.env.RABBIT_SERVER], { connectionOptions: opt });
> ```
> 
> ?

thanks, this fixed the issue
