### ISSUE TITLE
fix: missing `return` in promise chain

### ISSUE THREAD

**Issue by getlarge** [jwalton/node-amqp-connection-manager#171]
Hi,

I just came across that warning in a project :
```
Warning: a promise was created in a handler at ******/node_modules/amqp-connection-manager/dist/cjs/AmqpConnectionManager.js:207:22 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.attempt.Promise.try (******/node_modules/bluebird/js/release/method.js:29:9)
```

I suppose that returning null in `amqp.connect` called [here](https://github.com/jwalton/node-amqp-connection-manager/blob/master/src/AmqpConnectionManager.ts#L317) will solve the issue.
Should i create a PR ?

**Comment by jwalton** [comment]
I just removed that [`return null`](https://github.com/jwalton/node-amqp-connection-manager/blob/v3.3.0/src/AmqpConnectionManager.js#L207) because I thought it wasn't doing anything.  :P  This is some Bluebird thing I take it?

Thanks for the heads up!

**Comment by getlarge** [comment]
Thanks that was fast.
Yes that's a [bluebird](http://goo.gl/rRqMUw) thing, still they are right that sometimes it's better to be explicit.
