### ISSUE TITLE
PublishOptions type too restrictive in 3.7.0

### ISSUE THREAD

**Issue by pehlert** [jwalton/node-amqp-connection-manager#188]
The `PublishOptions` type that was introduced in 3.7.0 is too restrictive. We use the `options` parameter to pass some amqp options other then `timeout` and that fails now.

http://www.squaremobius.net/amqp.node/channel_api.html#channel_publish

**Comment by luddd3** [comment]
The new `PublishOptions` type is just the amqplib `Options.Publish` extended with a `timeout,` like this:
```typescript
interface PublishOptions extends Options.Publish {
    timeout?: number;
}
```

It should not be more restrictive than before, but my knowledge of TypeScript isn't the best. Do you have an example of something that fails?

**Comment by mariomurrent-softwaresolutions** [comment]
Why is this type not exported?

**Comment by jwalton** [comment]
Exported as `Options.Publish` in v4.1.2.

**Comment by mariomurrent-softwaresolutions** [comment]
@jwalton thank you very much :)

**Comment by jwalton** [comment]
(Oops - the publish failed.  Just a sec, it will in v4.1.2 in just a moment.  :) )

**Comment by jwalton** [comment]
Published.

**Comment by MahmudulHassan5809** [comment]
```
export interface PublishOptions extends Options.Publish {
    /** Message will be rejected after timeout ms */
    timeout?: number;
}
```
PublishOptions doesnot extends from Options.Publish . can pass others option value except timeout .. 
any solution
