### ISSUE TITLE
CVE : dependencies : url-parse - https://github.com/advisories/GHSA-hh27-ffr2-f2jc

### ISSUE THREAD

**Issue by SSANSH** [jwalton/node-amqp-connection-manager#229]
amqp-connection-manager is link to amqplib 0.8.0 and also to url-parse 1.5.1

└─┬ amqp-connection-manager@4.1.1
  └─┬ amqplib@0.8.0
    └── url-parse@1.5.1

url-parse  <=1.5.5
Severity: high
Open redirect in url-parse - https://github.com/advisories/GHSA-hh27-ffr2-f2jc
Authorization bypass in url-parse - https://github.com/advisories/GHSA-rqff-837h-mm52

please update amqplib to the latest version

Thanks.

**Comment by jwalton** [comment]
Hi @SSANSH.  Unfortunately there's nothing for amqp-connection-manager to do here - we don't have a direct dependency on amqplib, only a peer-dependency.  Even if we did, our dependency is on `amqplib@^0.8.0`, and 0.8.0 is the latest version of amqplib.  If you want to upgrade `url-parse`, then if you're using npm run:

```
npm upgrade --depth 2 url-parse
```

Or if you're using yarn:

```
yarn upgrade amqplib
```

If that doesn't fix it for you, see [this article](http://www.thedreaming.org/2022/02/22/nodejs-indirect-dependencies/) for more details about how to solve these kinds of issues, or point me to a copy of your `package.json` and `package-lock.json` (or `yarn.json`) and I'll see if I can help out.
