### ISSUE TITLE
ERROR 35382 Message Queue connect fail Error

### ISSUE THREAD

**Issue by vsiryxm** [jwalton/node-amqp-connection-manager#233]
When the producer establishes a connection, an error is reported：

ERROR 35382 Message Queue connect fail Error: Must supply either `urls` or `findServers`

**Comment by vsiryxm** [comment]
see code here：https://gist.github.com/vsiryxm/e074a5ea3c87f860972270ff6b549bc8

**Comment by vsiryxm** [comment]
It's solved, thanks

**Comment by vsiryxm** [comment]
请直接在QQ上联系我,谢谢!

**Comment by jwalton** [comment]
![image](https://user-images.githubusercontent.com/1771003/156207943-bc36308e-cc2f-4574-a12b-a48dac2651db.png)
