### ISSUE TITLE
import pb from 'promise-breaker' -> import * as pb from 'promise-breaker'

### ISSUE THREAD

**Issue by tomas0011** [jwalton/node-amqp-connection-manager#234]
Hello, I would like to acquire a small change in the import of `promise-breaker` since it does not export modules and its last update is 2 years ago (at the time of this post).
The change is simple, instead of importing the default is to import all the content, I leave images:
![image](https://user-images.githubusercontent.com/58223692/162045784-88430e19-33cf-4287-9918-df58ca70c4a3.png)

**Comment by jwalton** [comment]
I can make this update.  I can also push an update to promise-breaker if you want one?

**Comment by tomas0011** [comment]
Actually it is not necessary, since with that change everything would be working as it should. Thanks!

**Comment by tomas0011** [comment]
Hello, how long can it take to make the change?
is that this bug could delay a deployment and we depend on you

**Comment by kevit-manan-mankodi** [comment]
Hi there, any updates here? I am also unable to build my project due to this issue

![Screenshot-4](https://user-images.githubusercontent.com/97290047/182774814-ff34f361-a7ad-4426-bb8f-a7542ae425df.png)
.

**Comment by luddd3** [comment]
Is there any reason for not using the esModuleInterop flag set to true?

**Comment by kevit-manan-mankodi** [comment]
As that gives me the following error at 100+ places:

` A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.`

While I know using a default import or import require would be the correct way according to ES6 modules spec, currently I can't afford to make changes at 100+ places & test those - instead it would be much better for me if I can make everything work without the esModuleInterop flag set to true.

**Comment by jwalton** [comment]
I've pushed an alternative fix that involves fixing the exports for promise-breaker.  Let me know if this doesn't solve your issue!
