### ISSUE TITLE
Get error on exchange create 

### ISSUE THREAD

**Issue by MahmudulHassan5809** [jwalton/node-amqp-connection-manager#251]
```
@CommandHandler(PublishCommand)
export class PublishCommandHandler implements ICommandHandler<PublishCommand> {
    async execute(PublishCommand: PublishCommand) {
        try {
            console.log('OTP Object', PublishCommand.obj);
            console.log('RabbitMQ:', process.env.RABBITMQ_URL);
            const connection = amqp.connect(process.env.RABBITMQ_URL);

            const channel = connection.createChannel();
            await channel.assertExchange(
                PublishCommand.exchange,
                PublishCommand.exchangeType,
                {
                    durable: true,
                },
            );
            // await channel.assertexchange(exchange);
            await channel.publish(
                PublishCommand.exchange,
                PublishCommand.routingKey,
                Buffer.from(JSON.stringify(PublishCommand.obj)),
            );
        } catch (error) {
            console.log(error, '---------------');
        }
    }
}
```
when i want create new exchange type it gives me this error . but other time it  works fine
it gives me this error 
2022-06-28 11:15:41.870917+00:00 [error] <0.846.0> Channel error on connection <0.837.0> (172.18.0.5:51070 -> 172.18.0.3:5672, vhost: 'myvhost', user: 'myuser'), channel 1:
rabbitmq_1      | 2022-06-28 11:15:41.870917+00:00 [error] <0.846.0> operation basic.publish caused a channel exception not_found: no exchange 'user-create' in vhost 'myvhost'
nest_auth_service | Error: channel closed
any help how can solve this issue.
Thanks

**Comment by rhsobr** [comment]
If you're opening a new connection just before publishing a message, I'm afraid to say that the connection is not ready to be able to assert the exchange.

I suggest you open an AMQP connection in the app startup (or smth like that) and reuse this connection.

Let us know if it fixes.

**Comment by jwalton** [comment]
As noted in the example in the README.md, you need to do your channel setup (i.e. `assertExchange()`) inside a channel setup function:

```ts
@CommandHandler(PublishCommand)
export class PublishCommandHandler implements ICommandHandler<PublishCommand> {
  async execute(PublishCommand: PublishCommand) {
    try {
      console.log("OTP Object", PublishCommand.obj);
      console.log("RabbitMQ:", process.env.RABBITMQ_URL);
      const connection = amqp.connect(process.env.RABBITMQ_URL);

      const channel = connection.createChannel({
        setup: async function (channel) {
          await channel.assertExchange(
            PublishCommand.exchange,
            PublishCommand.exchangeType,
            { durable: true }
          );
        },
      });
      // await channel.assertexchange(exchange);
      await channel.publish(
        PublishCommand.exchange,
        PublishCommand.routingKey,
        Buffer.from(JSON.stringify(PublishCommand.obj))
      );
    } catch (error) {
      console.log(error, "---------------");
    }
  }
}

```

If you create a new channel, and then call `assertExchange()` on the new channel object, there's a good chance the channel will not have connected yet, in which case [assertExchange will do nothing](https://github.com/jwalton/node-amqp-connection-manager/blob/a1092b3a3a8e866080a1b400cd826a8edb739e3d/src/ChannelWrapper.ts#L897).  Putting it in the setup function means it will be automatically run every time the underlying channel reconnects, and your publishes will be queued until after the setup function is run.

**Comment by MahmudulHassan5809** [comment]
yup it was fixed . Thanks .
