### ISSUE TITLE
can not pass options to PublishOptions. only accept timeout 

### ISSUE THREAD

**Issue by MahmudulHassan5809** [jwalton/node-amqp-connection-manager#252]
```
export interface PublishOptions extends Options.Publish {
    /** Message will be rejected after timeout ms */
    timeout?: number;
}
```
PublishOptions extends Options.Publish class but can not use other options. Here i want to pass  contentType: '' as options parameter but it gives me type error.

please help me to solve this problem .
thanks in advance.

**Comment by yamilfrich** [comment]
Same here, but it seems like you can just install `@types/amqplib` and it should be solved.

**Comment by jwalton** [comment]
Installing @types/amqplib is probably the best fix here.  We could export the type in this library, but then there's a danger the version we have installed with conflict with the version you have installed.  We could make it a peer dependency, like we do with `amqplib`, but that just means you'd have to install it.
