### ISSUE TITLE
Null Message Exception for 404 Errors Skipped in amqplib >= 0.10.0

### ISSUE THREAD

**Issue by lance-menard** [jwalton/node-amqp-connection-manager#301]
It appears that amqplib versions >= 0.10.0 no longer have an `isOperational` flag on errors, causing the specific 404 exception linked below to no longer gracefully skip throwing an error.  I'm unclear what that flag is intended to communicate - documentation is scarce - so I'm not sure what the impact might be of removing it for versions of amqplib < 0.10.0.

https://github.com/jwalton/node-amqp-connection-manager/blob/master/src/ChannelWrapper.ts#L762

Reproducing the issue is fairly straightforward: install amqplib >= 0.10.0 alongside the amqp-connection-manager, create a channel and bind and consume from a queue, then delete that queue via the RabbitMQ admin dashboard or API.  In older versions of amqplib, the connection manager disconnects, then reconnects automatically and reruns the setup function to recreate the queue, as described in the comment.  In newer versions, the error is instead thrown and bubbles up.

**Comment by luddd3** [comment]
I think `isOperational` was used to communicate whether the channel was still usable or not.

**Comment by lance-menard** [comment]
Interesting.  It looks to me like the only PR included in v0.10.0 of amqplib is [this one](https://github.com/amqp-node/amqplib/pull/689).  I can't see anything in there that would obviously have caused that property to vanish - but then again, I don't see anything at all related to that property, so I'm not entirely clear where it was coming from in the first place.

This does bring to light a related problem, which is that if the `.catch()` attached to `_reconnectConsumer` throws on [line 770](https://github.com/jwalton/node-amqp-connection-manager/blob/master/src/ChannelWrapper.ts#L770), the error becomes an unhandled promise rejection.  As documented [here](https://www.rabbitmq.com/consumer-cancel.html), this can happen in a clustered scenario when the node hosting a queue is failing.  That's better than just swallowing the error entirely, but it seems to me it might be better to emit an error event on the channel and try to reconnect if the channel consumption is cancelled for any reason.  Thoughts?
