### ISSUE TITLE
Type ChannelWrapper gets error when using at NestJS service's constructor

### ISSUE THREAD

**Issue by liv1n9** [jwalton/node-amqp-connection-manager#305]
We are using `amqp-connection-manager` for a NestJS project. We have a channel wrapper provider injected into a service:
```typescript
import { ChannelWrapper } from "amqp-connection-manager";

export class RabbitMQSetupService implements OnModuleInit {
    constructor(
        @InjectRabbitMQChannel()
        private readonly rmqChannel: ChannelWrapper,
    ) { }
}
```
Then we get this error:
```
ReferenceError: ChannelWrapper is not defined
    at Object.<anonymous> (/home/ubuntu/rmq/src/modules/sync/service/rabbitmq-setup.service.ts:16:29)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/livw/Desktop/Project/rocketchat-sync/src/modules/sync/sync.module.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

But if we write the constructor like below, it works:
```typescript
@Injectable()
export class RabbitMQSetupService implements OnModuleInit {
    private rmqChannel: ChannelWrapper;

    constructor(
        @InjectRabbitMQChannel()
        rmqChannel: any,
    ) {
        this.rmqChannel = rmqChannel;
    }
}
```
This also doesn't work:
```typescript
@Injectable()
export class RabbitMQSetupService implements OnModuleInit {
    private rmqChannel: ChannelWrapper;

    constructor(
        @InjectRabbitMQChannel()
        rmqChannel: ChannelWrapper,
    ) {
        this.rmqChannel = rmqChannel;
    }
}
```
Any idea to fix it?

**Comment by microwavekonijn** [comment]
https://github.com/jwalton/node-amqp-connection-manager/pull/249

Temp fix I found it to define a type alias and use that instead, like:
```ts
type ChannelWrapperAlias = ChannelWrapper;

class Foo {
  constructor(channel: ChannelWrapperAlias) {}
}
```

**Comment by jwalton** [comment]
Can someone post a minimal reproduction repo for this?  Or tell me a fast way to set up such a thing?  I'm afraid I'm not a NestJS user, and I don't want to spend hours learning NestJS to play with this issue.  :P

I wonder if this has something to do with the fact that ChannelWrapper is a `class`, but is exported only as a type?  If creating a type alias fixes it, maybe if we made an actual TypeScript interface it would fix it too?

**Comment by microwavekonijn** [comment]
So as far as I understand it is not something specific to NestJS, but rather Typescripts `emitDecoratorMetadata` and `experimentalDecorators`. A snippet like this would explain best:
```ts
const Dec: ClassDecorator = () => undefined;

class Bar {}

interface Baz {} 

@Dec
class Foo {
    constructor(a: Bar, b: Baz) {}
}
```
[TS Playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAIgU2ALhgYQDYEMIUaAJyyhAJgF4YAKASgoD4YBXMAEwQDMBLMBVgbgBQg4NlwwAQljIBvAL7CeUBAQ5ZgCSVgBeMeTGEABfCLEQYAMRAg9gmPZihIUAk2AkCVLKikEANDAARj46dPKCckA)

The compiled script will include:
```js
__metadata("design:paramtypes", [Bar, Object])
```
What is expected is that `ChannelWrapper` would become `Object` like `Baz`, however it is compiled as if it is a class like `Bar`. As it is not available during runtime it causes a rather confusing error. Exporting it normally would fix the problem, though in hindsight this should probably addressed as a bug in Ts. Your call.
