### ISSUE TITLE
Connect promise

### ISSUE THREAD

**Issue by Shahar-Ben-Ezra** [jwalton/node-amqp-connection-manager#319]
Hi,
Thanks for your amazing package, I handle a problem with the connect method. 
One of my health checks to realize if the pod is ready is to check if the connection to Rabbit is connected.
when I am using the connect method I realize that the method is not waiting to connect to Rabbit.
my questions are-
 why not wrap conn.connect() with await?
 if its ok to get the conn obj and then call again to the conn.connect() with await?

For example

```
conn = amqp.connect([process.env.RABBIT_CONNECTION_STRING ]);
await conn.connect();
```

Thanks, Shahar.

**Comment by luddd3** [comment]
I am not entirely sure if I understand your question, but you can create and wait for a connection like this.

```javascript
const AmqpConnectionManager = require('amqp-connection-manager')
  .AmqpConnectionManagerClass
const connection = new AmqpConnectionManager(connectionOptions)
await connection.connect()
```

**Comment by Shahar-Ben-Ezra** [comment]
Thanks that's what I have done
