### ISSUE TITLE
How to unbind a routing key from a queue?

### ISSUE THREAD

**Issue by xfd1387** [jwalton/node-amqp-connection-manager#320]

**Comment by jwalton** [comment]
I'm guessing you're looking for [`unbindQueue()`](https://amqp-node.github.io/amqplib/channel_api.html#channel_unbindQueue)?

But, `node-ampq-connection-manager` is just focused on reconnecting [amqplib](https://amqp-node.github.io/amqplib/) when it disconnects.  This is a question you'd be better off asking on stackoverflow.com.

**Comment by ewenjo** [comment]
Just ran into this as well. Can we get the PR merged?

**Comment by ewenjo** [comment]
@jwalton Possible to take another look?

**Comment by jwalton** [comment]
Ahhh.  Fixed in 4.1.11.  Thanks @xfd1387 and @ewenjo for hitting me with a clue stick.  ;) And sorry this took so long to get merged.
