### ISSUE TITLE
How to resend queue if fail?

### ISSUE THREAD

**Issue by dwiyudirayia** [jwalton/node-amqp-connection-manager#322]
Hello guys. I have issue when send the queue. How to resend queue if fail?

**Comment by dwiyudirayia** [comment]
`const amqp = require('amqp-connection-manager');
const configAmqp = require("../../../config/amqp.js");
const moment = require("moment");
const { error } = require('../../../log');

exports.heartbeat = function (msg) {
    const amqpSsl = configAmqp.ssl == true || configAmqp.ssl == 'true' ? 'amqps' : 'amqp';
    const opt = { credentials: require('amqplib').credentials.plain(configAmqp.user, configAmqp.password) };
    const queue = configAmqp.queueHeartbeat
    const connection = amqp.connect([amqpSsl + '://' + configAmqp.host + ':' + configAmqp.port],{connectionOptions: opt});
    // Create a channel wrapper
    const channelWrapper = connection.createChannel({
        json: true,
        setup: function(channel) {
            // `channel` here is a regular amqplib `ConfirmChannel`.
            return channel.assertQueue(queue, {durable: true});
        }
    });

    // Send messages until someone hits CTRL-C or something goes wrong...
    const sendMessage = function() {
        channelWrapper.sendToQueue(queue, {
            date: moment().format("YYYY-MM-DD HH:mm:ss")
        })
        .then(function() {
            console.log("Message sent heartbeat");
        })
        .catch(function(err) {
            console.log("Message was rejected heartbeat:", err.stack);
            const payload = [
                {
                    title: 'Message',
                    value: err.message,
                    short: false,
                },
                {
                    title: 'File',
                    value: 'Producer heartbeat',
                    short: false,
                },
            ]
            error(process.env.LOG_SLACK_AMB_LOG_ERROR_WEBHOOK_URL, payload);
        }).finally(function() {
            channelWrapper.close();
            connection.close();
        });
    };

    console.log("Sending messages heartbeat...");
    sendMessage();
};
`

**Comment by jwalton** [comment]
Since `sendToQueue()` will reject if the message can't be sent, you can do something like:

```ts
async function sendMessage(retriesLeft=5) {
  try {
    await channelWrapper.sendToQueue(...);
  } catch(err) {
      if (retriesLeft > 0) {
        // Wait a bit before we retry
        await new Promise((resolve) => setTimeout(resolve, 5000));
        sendMessage(retriesLeft - 1);
      }
  }
}
```

**Comment by dwiyudirayia** [comment]
Okaay thanks brother. I got it
